// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AnswerExtras string
	Answers      string
	Owners       string
	Records      string
}{
	AnswerExtras: "answer_extras",
	Answers:      "answers",
	Owners:       "owners",
	Records:      "records",
}
