// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AnswerDetails string
	Answers       string
	Owners        string
	Records       string
}{
	AnswerDetails: "answer_details",
	Answers:       "answers",
	Owners:        "owners",
	Records:       "records",
}
