// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AnswerExtras", testAnswerExtrasUpsert)
	t.Run("Answers", testAnswersUpsert)
	t.Run("Owners", testOwnersUpsert)
	t.Run("Records", testRecordsUpsert)
}
